const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.TiledBg,
		C3.Plugins.Sprite,
		C3.Behaviors.scrollto,
		C3.Behaviors.EightDir,
		C3.Plugins.Tilemap,
		C3.Behaviors.solid,
		C3.Plugins.Shape3D,
		C3.Behaviors.Pathfinding,
		C3.Behaviors.LOS,
		C3.Behaviors.MoveTo,
		C3.Plugins.Keyboard,
		C3.Plugins.Text,
		C3.Plugins.Button,
		C3.Behaviors.Anchor,
		C3.Plugins.Audio,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Plugins.Sprite.Acts.SetTowardPosition,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.Sprite.Acts.SetX,
		C3.Plugins.Sprite.Exps.Angle,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.Sprite.Cnds.OnCreated,
		C3.Behaviors.MoveTo.Acts.MoveToPosition,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Sprite.Acts.SetFlipped,
		C3.Plugins.Text.Acts.SetAngle,
		C3.Plugins.Text.Acts.SetPos,
		C3.Plugins.Keyboard.Cnds.IsKeyDown,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Button.Cnds.OnClicked
	];
};
self.C3_JsPropNameTable = [
	{TiledBackground: 0},
	{ScrollTo: 0},
	{"8Direction": 0},
	{Player: 0},
	{Tilemap: 0},
	{TiledBackground2: 0},
	{Solid: 0},
	{TiledBackground3: 0},
	{Tilemap2: 0},
	{TiledBackground4: 0},
	{"3DShape": 0},
	{Pathfinding: 0},
	{LineOfSight: 0},
	{MoveTo: 0},
	{Enemy: 0},
	{Keyboard: 0},
	{bullet: 0},
	{"3DShape2": 0},
	{cage: 0},
	{Sprite: 0},
	{zoneNum: 0},
	{zone: 0},
	{loseText: 0},
	{TiledBackground5: 0},
	{Text: 0},
	{retrybtn: 0},
	{flag: 0},
	{Text2: 0},
	{Anchor: 0},
	{killCounttxt: 0},
	{Audio: 0},
	{ZoneId: 0},
	{KillCount: 0}
];

self.InstanceType = {
	TiledBackground: class extends self.ITiledBackgroundInstance {},
	Player: class extends self.ISpriteInstance {},
	Tilemap: class extends self.ITilemapInstance {},
	TiledBackground2: class extends self.ITiledBackgroundInstance {},
	TiledBackground3: class extends self.ITiledBackgroundInstance {},
	Tilemap2: class extends self.ITilemapInstance {},
	TiledBackground4: class extends self.ITiledBackgroundInstance {},
	_3DShape: class extends self.I3DShapeInstance {},
	Enemy: class extends self.ISpriteInstance {},
	Keyboard: class extends self.IInstance {},
	bullet: class extends self.ISpriteInstance {},
	_3DShape2: class extends self.I3DShapeInstance {},
	Sprite: class extends self.ISpriteInstance {},
	zone: class extends self.ISpriteInstance {},
	loseText: class extends self.ITextInstance {},
	TiledBackground5: class extends self.ITiledBackgroundInstance {},
	Text: class extends self.ITextInstance {},
	retrybtn: class extends self.IButtonInstance {},
	flag: class extends self.ISpriteInstance {},
	Text2: class extends self.ITextInstance {},
	killCounttxt: class extends self.ITextInstance {},
	Audio: class extends self.IInstance {}
}